'use strict';

export default [
    "rock 'n' roll (https://vk.com/e_roll)",
    'classic rock (https://vk.com/e_music_rock)',
    'garage rock (https://vk.com/e_garage_rock)',
    'psychedelic rock (https://vk.com/e_music_psychedelic)',
    'progressive rock (https://vk.com/e_music_progrock)',
    'krautrock (https://vk.com/e_music_krautrock)',
    'folk rock (https://vk.com/e_folk_rock)',
    'country rock (https://vk.com/e_country_music)',
    'psychobilly (https://vk.com/e_psychobilly)',
    'surf rock (https://vk.com/e_music_surfrock)',
    'glam (https://vk.com/e_music_glam)',
    'alternative rock (https://vk.com/e_alternative__rock)',
    'britpop (https://vk.com/postbritpop)',
    'grunge (https://vk.com/e_grunge)',
    'noise rock (https://vk.com/e_music_noise_rock)',
    'fuzz rock (https://vk.com/e_fuzz)',
    'heavy psych (https://vk.com/heavypsych)',
    'stoner rock (https://vk.com/e_music_stonerrock)',
    'occult (https://vk.com/e_occult)',
    'space rock (https://vk.com/e_music_spacerock)',
    'neo & modern prog (https://vk.com/e_music_neoprog)',
    'math rock (https://vk.com/mathwall)',
    'post rock (https://vk.com/post_music)',
    'slowcore & sadcore (https://vk.com/e_slowcore)',
    'indie (https://vk.com/e_indie)',
    'new wave (https://vk.com/e_new_wave)',
    'coldwave (https://vk.com/e_coldwave)',
    'darkwave (https://vk.com/e_darkwave)',
    'shoegaze & post-punk (https://vk.com/postpunk_shoegaze)',
    'industrial (https://vk.com/e_music_industrial)',
    'gothic rock (https://vk.com/e_gothic_rock)',
    'deathrock (https://vk.com/deathr0ck)',
    'russian rock (https://vk.com/russ_rock)',
    'experimental rock (https://vk.com/experimental_music)',
    'avant-garde (https://vk.com/e_avantgarde)',
    'j-rock (https://vk.com/e_japan)',
    'k-rock (https://vk.com/e_korea)',
    'heavy metal (https://vk.com/e_heavy_metal)',
    'thrash metal (https://vk.com/e_thrash)',
    'speed metal (https://vk.com/public52654940)',
    'industrial metal (https://vk.com/e_industrial_metal)',
    'metalcore (https://vk.com/emetalcore)',
    'djent (https://vk.com/djent_music)',
    'progressive metal (https://vk.com/progressivemetal)',
    'post metal (https://vk.com/post_music)',
    'drone (https://vk.com/e_music_drone)',
    'doom (https://vk.com/e_doom)',
    'sludge (https://vk.com/e_sludge)',
    'occult (https://vk.com/e_occult)',
    'black metal (https://vk.com/blackwall)',
    'death metal (https://vk.com/e_death_metal)',
    'melodic death (https://vk.com/e.music.melodic_death)',
    'slamming brutal death (https://vk.com/slamming_brutal_death)',
    'gothic metal (https://vk.com/e_music_gothic_metal)',
    'power metal (https://vk.com/e_power)',
    'folk metal (https://vk.com/e_folk_metal)',
    'oriental metal (https://vk.com/e_oriental_metal)',
    'electronic metal (https://vk.com/exit_to_exist)',
    'metal covers (https://vk.com/e_metal_covers)',
    'punk (https://vk.com/e_punk)',
    'hardcore punk (https://vk.com/e_hardcore_punk)',
    'thrash (https://vk.com/thrash_zone)',
    'grind (https://vk.com/emusic_grind)',
    'crust (https://vk.com/e_crust)',
    'screamo (https://vk.com/e_screamo)',
    'midwest emo (https://vk.com/midwest_emo)',
    'ska (https://vk.com/e_music_ska)',
    'celtic punk (https://vk.com/e_music_folkpunk)',
    'shoegaze & post-punk (https://vk.com/postpunk_shoegaze)',
    'hardcore punk (https://vk.com/e_hardcore_punk)',
    'melodic hardcore (https://vk.com/e_melodic_hc)',
    'chaotic hardcore (https://vk.com/e_chaotic_hardcore)',
    'noisecore (https://vk.com/e_noisecore)',
    'grindcore (https://vk.com/emusic_grind)',
    'post-hardcore (https://vk.com/e_post_hardcore)',
    'metalcore (https://vk.com/emetalcore)',
    'deathcore (https://vk.com/e_music_deathcore)',
    'trancecore (https://vk.com/trancecore_music)',
    'nintendocore (https://vk.com/e_nintendo)',
    'rapcore (https://vk.com/wootdafck)',
    'horrorcore (https://vk.com/e_horrorcore)',
    'mathcore (https://vk.com/mathcore_music)',
    'jazzcore (https://vk.com/e_jazzcore)',
    'folk (https://vk.com/e_music_folk)',
    'authentic (https://vk.com/emusicauthentic)',
    'medieval (https://vk.com/musicmedieval)',
    'contemporary folk (https://vk.com/e_contemporary_folk)',
    'free folk (https://vk.com/e_free_folk)',
    'dark folk (https://vk.com/e_dark_folk)',
    'ritual (https://vk.com/ritual_music)',
    'sacred (https://vk.com/e_music_sacred)',
    'country (https://vk.com/e_country_music)',
    'tramp music (https://vk.com/e_music_tramp)',
    'riot folk (https://vk.com/riotfolk)',
    'folk rock (https://vk.com/e_folk_rock)',
    'folk metal (https://vk.com/e_folk_metal)',
    'ethnic eclectic (https://vk.com/e_ethnic_electronica)',
    'balkan, gypsy, jewish (https://vk.com/e_ethnicexotics)',
    'celtic (https://vk.com/e_celtic)',
    'afrobeat (https://vk.com/e_afrobeat)',
    'throatsinging (https://vk.com/throatsinging)',
    'tango (https://vk.com/e_tango)',
    'oriental metal (https://vk.com/e_oriental_metal)',
    'ussr music (https://vk.com/ussrmusic)',
    'russian rock (https://vk.com/russ_rock)',
    'red sons (https://vk.com/e_redsons)',
    'ukraine (https://vk.com/e__ukraine)',
    'estonia (https://vk.com/public101393585)',
    'korea (https://vk.com/e_korea)',
    'j-pop (https://vk.com/e_j_pop)',
    'japan (https://vk.com/e_japan)',
    'india (https://vk.com/e_music_india)',
    'musica brasileira (https://vk.com/e_music_musica_brasileira)',
    'iceland (https://vk.com/e_island)',
    'french chanson (https://vk.com/e_chanson)',
    'russian chanson (https://vk.com/e_russian_chanson)',
    'ambient (https://vk.com/e_music_ambient)',
    'minimal (https://vk.com/e_music_minimal)',
    'illbient (https://vk.com/e_illbient)',
    'downtempo (https://vk.com/e_downtempo)',
    'chillwave (https://vk.com/wavvy)',
    'trip-hop (https://vk.com/e_triphop)',
    'psybient (https://vk.com/e_music_psybient)',
    'vaporwave (https://vk.com/e_vaporwave)',
    'new age (https://vk.com/e_newage)',
    'lounge (https://vk.com/elounge)',
    'drone (https://vk.com/e_music_drone)',
    'ritual (https://vk.com/ritual_music)',
    'jazz (https://vk.com/e__jazz)',
    'smooth jazz (https://vk.com/e_smooth)',
    'nu-jazz (https://vk.com/e_nu_jazz)',
    'dark jazz (https://vk.com/e_dark_jazz)',
    'ethno jazz (https://vk.com/e_ethno_jazz)',
    'blues (https://vk.com/e_music_blues)',
    'delta blues (https://vk.com/delta_blues)',
    'archaic race music (https://vk.com/e_archaic_race_music)',
    'hip-hop (https://vk.com/e_music_hip_hop)',
    'cloud rap (https://vk.com/e_cloud_rap)',
    'french hip-hop (https://vk.com/e_french_hh)',
    'abstract hip-hop (https://vk.com/e_music_abstract_hiphop)',
    'trip-hop (https://vk.com/e_triphop)',
    'horrorcore (https://vk.com/e_horrorcore)',
    'wonky (https://vk.com/e_wonky)',
    'bass (https://vk.com/e_music_bass)',
    'drum & bass (https://vk.com/e_dnb)',
    'intelligent drum & bass (https://vk.com/e_intelligent)',
    'juke & footwork (https://vk.com/e_music_juke)',
    'neurofunk (https://vk.com/e_neurofunk)',
    'dubstep & uk garage (https://vk.com/e_ukgarage)',
    'wonky (https://vk.com/e_wonky)',
    'breakbeat (https://vk.com/e_breakbeat)',
    'breaks (https://vk.com/e_atmosphericbreaks)',
    'classicore (https://vk.com/emusic_classicore)',
    'breakcore (https://vk.com/emusic_breakcore)',
    'drumfunk (https://vk.com/e_drumfunk)',
    'jungle (https://vk.com/e_jungle)',
    'rave (https://vk.com/e_rave)',
    'electro (https://vk.com/e_electro)',
    'fidget (https://vk.com/e_finget_french)',
    'electropop (https://vk.com/e_music_electronic)',
    'synth (https://vk.com/e_synth)',
    'new beat (https://vk.com/e_newbeat)',
    'coldwave (https://vk.com/e_coldwave)',
    'darkwave (https://vk.com/e_darkwave)',
    'retrowave (https://vk.com/retrowave)',
    'futurepop (https://vk.com/e_futurepop)',
    'traditional electronic (https://vk.com/e_music_traditional_electronic)',
    'progressive electronic (https://vk.com/e_progelectronic)',
    'idm (https://vk.com/idmuziq)',
    'glitch (https://vk.com/e_glitch)',
    'witch house (https://vk.com/witch_house)',
    'vaporwave (https://vk.com/e_vaporwave)',
    'wonky (https://vk.com/e_wonky)',
    'chiptune, 8-bit (https://vk.com/e_music_8bit)',
    'nintendocore (https://vk.com/e_nintendo)',
    'funk (https://vk.com/funk_music)',
    'disco (https://vk.com/e_disco)',
    'industrial (https://vk.com/e_music_industrial)',
    'industrial metal (https://vk.com/e_industrial_metal)',
    'martial (https://vk.com/e_music_martial)',
    'ebm (https://vk.com/ebmusic)',
    'dark electro (https://vk.com/e_music_dark_electro)',
    'noise (https://vk.com/public26893663)',
    'rhythmic noise (https://vk.com/e_music_rhythmic_noise)',
    'techno (https://vk.com/e_techno)',
    'detroit techno (https://vk.com/e_detroit_techno)',
    'dub techno (https://vk.com/e_dub_techno)',
    'house (https://vk.com/e_music_house)',
    'trance (https://vk.com/e_music_trance)',
    'goa trance, psy trance (https://vk.com/e_music.psytrance)',
    'art (https://vk.com/eartmusic)',
    'contemporary classical (https://vk.com/contemporary_classical)',
    'neoclassical (https://vk.com/e_neoclassical)',
    'avant-garde (https://vk.com/e_avantgarde)',
    'opera (https://vk.com/public_opera)',
    'medieval (https://vk.com/musicmedieval)',
    'classicore (https://vk.com/emusic_classicore)',
    'experimental (https://vk.com/experimental_music)',
    'avant-garde (https://vk.com/e_avantgarde)',
    'art pop (https://vk.com/e_art_pop)',
    'improvisation (https://vk.com/impromus)',
    'progressive electronic (https://vk.com/e_progelectronic)',
    'nww list (https://vk.com/e_nww)',
    'spoken word (https://vk.com/e_spoken_word)',
    'field recording (https://vk.com/e_music_field_recording)',
    'outsider (https://vk.com/outsider_music)',
    'acoustic (https://vk.com/real_voice)',
    'a cappella (https://vk.com/e_music_acapella)',
    'covers (https://vk.com/e_music_cover)',
    'original soundtrack (https://vk.com/moviesost)',
    'kircore (https://vk.com/e_kircore)',
    'dark cabaret (https://vk.com/dark_cabaret)',
    'french chanson (https://vk.com/e_chanson)',
    'russian chanson (https://vk.com/e_russian_chanson)',
    'sacred (https://vk.com/e_music_sacred)'
];
